[build]
  command = "DISABLE_ESLINT_PLUGIN=true NEXT_DISABLE_TYPECHECK=true npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# ✅ Top-level ignore_secrets (not tied to Lighthouse)
ignore_secrets = [
  "VITE_SANITY_PROJECT_ID",
  "VITE_SANITY_DATASET",
  "VITE_SANITY_API_VERSION",
  "NEXT_PUBLIC_SANITY_PROJECT_ID",
  "NEXT_PUBLIC_SANITY_DATASET",
  "NEXT_PUBLIC_SANITY_API_VERSION"
]
