[build]
  command = "DISABLE_ESLINT_PLUGIN=true NEXT_DISABLE_TYPECHECK=true npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NETLIFY_DISABLE_SECRET_SCANNING = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
